version: "3.5"
x-environment:
  &QUICKSTART_ENVIRONMENT # These are read from .env file. The values in the .env file maybe overriden by shell envvars
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  PLAID_ENV: ${PLAID_ENV}
services:
  go:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./go/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  java:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./java/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  node:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./node/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  python:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./python/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  ruby:
    networks:
      - "quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./ruby/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
      - REACT_APP_COGNITO_REGION=${AWS_REGION}
      - REACT_APP_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - REACT_APP_USER_POOL_WEB_CLIENT_ID=${COGNITO_CLIENT_ID}
    volumes:
      - ./frontend:/app
      - /app/node_modules
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
networks:
  quickstart:
    name: quickstart
