name: Terraform Deployment (Test)

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action (apply or destroy)'
        required: true
        default: 'apply'


jobs:
  terraform:
    name: Terraform Deployment (Test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.LEO_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.LEO_SECRET_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: fisc-ai

      - name: Validate Terraform
        run: terraform validate
        working-directory: fisc-ai

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: fisc-ai
        env:
          TF_VAR_github_token: ${{ secrets.TOKEN_GIT }}

      - name: Apply Terraform
        if: github.event.inputs.action == 'apply' || github.ref == 'refs/heads/test'
        run: terraform apply -auto-approve tfplan
        working-directory: fisc-ai
        env:
          TF_VAR_github_token: ${{ secrets.TOKEN_GIT }}

      - name: Get and Write Clean API URL
        id: get_api_url
        working-directory: fisc-ai
        shell: bash
        run: |
          echo "Fetching clean API URL from Terraform output..."
          raw_output=$(terraform output -raw api_gateway_url 2>/dev/null)
          api_url=$(echo "$raw_output" | sed 's/::.*//' | grep -oE '^https://[^[:space:]]+')
          echo "Cleaned API URL: $api_url"
          safe_url="${api_url//'%'/'%25'}"
          safe_url="${safe_url//$'\n'/'%0A'}"
          safe_url="${safe_url//$'\r'/'%0D'}"
          echo "REACT_APP_API_URL=$safe_url" >> $GITHUB_ENV
          echo "REACT_APP_API_URL=$api_url" > ../fisc-ai/frontend/.env.production

      - name: Debug .env.production
        working-directory: fisc-ai/frontend
        run: cat .env.production

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: fisc-ai
        env:
          TF_VAR_github_token: ${{ secrets.TOKEN_GIT }}
